(function() {
    window.MoonKatData = {
        userPrefixes: [
            "Crypto", "Diamond", "Paper", "Moon", "Rocket", "Cyber", "Techno", "Mega", "Giga", "Ultra",
            "Super", "Hyper", "Master", "Lord", "King", "Queen", "Prince", "Princess", "Duke", "Baron",
            "Captain", "Major", "General", "Admiral", "Space", "Star", "Solar", "Lunar", "Nebula", "Void",
            "Quantum", "Neural", "Digital", "Virtual", "Binary", "Code", "Data", "Net", "Web", "Chain",
            "Block", "Coin", "Token", "Asset", "Value", "Wealth", "Rich", "Gold", "Silver", "Platinum",
            "Bronze", "Copper", "Iron", "Steel", "Titanium", "Neon", "Laser", "Plasma", "Flux", "Wave",
            "Pulse", "Vibe", "Flow", "Drift", "Shift", "Speed", "Fast", "Slow", "Steady", "Stable",
            "Bull", "Bear", "Whale", "Shark", "Dolphin", "Fish", "Crab", "Shrimp", "Wolf", "Lion",
            "Tiger", "Eagle", "Hawk", "Falcon", "Owl", "Raven", "Crow", "Phoenix", "Dragon", "Wyvern",
            "Ghost", "Phantom", "Shadow", "Spirit", "Soul", "Mind", "Brain", "Thought", "Idea", "Concept",
            "Alpha", "Beta", "Gamma", "Delta", "Omega", "Zero", "One", "Prime", "Core", "Nexus",
            "Base", "Foundation", "Origin", "Source", "Root", "Seed", "Spark", "Flame", "Fire", "Ice",
            "Frost", "Snow", "Storm", "Thunder", "Lightning", "Rain", "Wind", "Air", "Earth", "Water",
            "Red", "Blue", "Green", "Yellow", "Orange", "Purple", "Violet", "Indigo", "Black", "White",
            "Grey", "Dark", "Light", "Bright", "Dim", "Faint", "Clear", "Sharp", "Blur", "Haze",
            "Lucky", "Happy", "Sad", "Mad", "Glad", "Angry", "Calm", "Cool", "Hot", "Cold",
            "Big", "Small", "Tiny", "Huge", "Giant", "Massive", "Micro", "Nano", "Pico", "Femto",
            "Doge", "Pepe", "Shiba", "Floki", "Kishu", "Akita", "Hoge", "Mona", "Cate", "Feg",
            "Safe", "Risk", "High", "Low", "Top", "Bottom", "Peak", "Dip", "Crash", "Pump",
            "Dump", "Hold", "Sell", "Buy", "Trade", "Swap", "Farm", "Stake", "Yield", "Mint",
            "Burn", "Gas", "Fee", "Tax", "Limit", "Stop", "Loss", "Gain", "Profit", "Debt"
        ],
        userSuffixes: [
            "Hands", "Boy", "Girl", "Man", "Woman", "Guy", "Gal", "Kid", "Lad", "Lass",
            "Trader", "Hodler", "Miner", "Farmer", "Staker", "Buyer", "Seller", "Flipper", "Sniper", "Bot",
            "Droid", "Cyborg", "Machine", "Engine", "System", "Network", "Matrix", "Grid", "Loop", "Link",
            "Node", "Hub", "Port", "Gate", "Door", "Key", "Lock", "Vault", "Safe", "Chest",
            "Wallet", "Bag", "Sack", "Pocket", "Purse", "Bank", "Fund", "Trust", "Stock", "Share",
            "Bond", "Option", "Future", "Swap", "Deriv", "Index", "Rate", "Price", "Cost", "Val",
            "Cap", "Vol", "Liq", "Lev", "Marg", "Pos", "Ord", "Bid", "Ask", "Spr",
            "Wiz", "Guru", "Pro", "Noob", "Newb", "Vet", "Ace", "Champ", "Star", "Legend",
            "God", "Demi", "Hero", "Villain", "Rogue", "Scout", "Spy", "Agent", "Op", "Exec",
            "Boss", "Chief", "Head", "Lead", "Main", "Top", "High", "Max", "Min", "Mid",
            "X", "Y", "Z", "V2", "V3", "Pro", "Max", "Lite", "Mini", "Ultra",
            "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
            "100", "1000", "9000", "420", "69", "777", "888", "360", "247", "365",
            "Walker", "Runner", "Jumper", "Flyer", "Pilot", "Driver", "Rider", "Surfer", "Sailor", "Diver",
            "Hunter", "Seeker", "Finder", "Keeper", "Loser", "Winner", "Gainer", "Saver", "Spender", "User",
            "Maker", "Builder", "Creator", "Dev", "Coder", "Hacker", "Mod", "Admin", "Sys", "Root",
            "Fan", "Stan", "Simp", "Buff", "Nerd", "Geek", "Freak", "Weeb", "Otaku", "Dork",
            "Verse", "World", "Land", "Zone", "Area", "Region", "Sector", "Field", "Space", "Room"
        ],
        userSingles: [
            "Satoshi", "Vitalik", "Elon", "Cz", "Armstrong", "Saylor", "Powell", "Gensler", "Yellen", "Buffett",
            "Munger", "Dalio", "Soros", "Icahn", "Simons", "Griffin", "Cohen", "Tepper", "Paulson", "Ackman",
            "Bezos", "Gates", "Jobs", "Zuck", "Page", "Brin", "Ellison", "Ballmer", "Dell", "Knight",
            "Crypto", "Bitcoin", "Ethereum", "Ripple", "Cardano", "Solana", "Polkadot", "Dogecoin", "Shiba", "Litecoin",
            "Tron", "Avalanche", "Uniswap", "Chainlink", "Polygon", "Stellar", "Cosmos", "VeChain", "Theta", "Filecoin",
            "Monero", "Eos", "Aave", "Klaytn", "Neo", "Iota", "Maker", "Tezos", "Algorand", "Dash",
            "Zcash", "Nem", "Qtum", "Omg", "Icon", "Lisk", "Nano", "Ont", "Zil", "Bat",
            "Hodl", "Fomo", "Fud", "Rekt", "Moon", "Lambo", "Wagmi", "Ngmi", "Dyor", "Ky",
            "Bull", "Bear", "Whale", "Shrimp", "Crab", "Fish", "Shark", "Dolphin", "Orca", "Seal",
            "Gold", "Silver", "Bronze", "Copper", "Iron", "Steel", "Tin", "Zinc", "Lead", "Coal",
            "Oil", "Gas", "Corn", "Wheat", "Soy", "Rice", "Sugar", "Cotton", "Cocoa", "Coffee",
            "Alpha", "Omega", "Delta", "Sigma", "Zeta", "Theta", "Kappa", "Lambda", "Mu", "Nu"
        ],
        coinPrefixes: [
            "Moon", "Safe", "Baby", "Elon", "Doge", "Shiba", "Pepe", "Floki", "Kishu", "Akita",
            "Cum", "Ass", "Porn", "Sex", "Weed", "Pot", "Dope", "High", "Stoned", "Trippy",
            "Mars", "Venus", "Saturn", "Jupiter", "Pluto", "Uranus", "Neptune", "Mercury", "Earth", "Sun",
            "Galactic", "Cosmic", "Inter", "Uni", "Multi", "Poly", "Meta", "Mega", "Giga", "Tera",
            "Super", "Hyper", "Ultra", "Uber", "Power", "Force", "Energy", "Speed", "Fast", "Quick",
            "Smart", "Intelli", "Genius", "Brain", "Mind", "Neuro", "Cyber", "Techno", "Robo", "Mech",
            "Bio", "Eco", "Green", "Clean", "Pure", "Fresh", "Nature", "Wild", "Free", "Open",
            "Gold", "Silver", "Diamond", "Gem", "Jewel", "Ruby", "Emerald", "Sapphire", "Pearl", "Crystal",
            "Royal", "Regal", "King", "Queen", "Prince", "Lord", "Duke", "Baron", "Noble", "Elite",
            "Rich", "Wealth", "Money", "Cash", "Coin", "Token", "Asset", "Fund", "Bank", "Trust",
            "Yield", "Farm", "Stake", "Pool", "Swap", "Dex", "Defi", "Cefi", "Nft", "Dao",
            "Web3", "Net", "Link", "Chain", "Block", "Node", "Hash", "Code", "Data", "Bit"
        ],
        coinSuffixes: [
            "Coin", "Token", "Protocol", "Network", "Chain", "Swap", "Finance", "Cash", "Money", "Gold",
            "Dao", "Nft", "Verse", "Land", "World", "City", "Town", "Ville", "Base", "Hub",
            "Lab", "Labs", "Inc", "Corp", "Ltd", "Group", "Team", "Dev", "System", "Sys",
            "App", "Dapp", "Soft", "Ware", "Tech", "Tool", "Box", "Kit", "Set", "Gear",
            "Pad", "Launch", "Start", "Begin", "Rise", "Up", "Go", "Run", "Fly", "Jet",
            "Moon", "Mars", "Star", "Sun", "Sky", "Space", "Void", "Orbit", "Path", "Way",
            "Gate", "Port", "Door", "Key", "Lock", "Safe", "Vault", "Store", "Shop", "Mart",
            "Bet", "Gamble", "Win", "Lose", "Play", "Game", "Fun", "Joy", "Happy", "Luck",
            "Inu", "Doge", "Cat", "Neko", "Ape", "Kong", "Wolf", "Bear", "Bull", "Pig",
            "X", "Y", "Z", "V2", "V3", "Pro", "Max", "Plus", "One", "Zero"
        ],
        coinSingles: [
            "Bitcoin", "Ethereum", "Ripple", "Litecoin", "Cardano", "Polkadot", "Stellar", "Chainlink", "Dogecoin", "Tether",
            "Solana", "Uniswap", "Binance", "Terra", "Avalanche", "VeChain", "Tron", "Monero", "Eos", "Tezos",
            "Neo", "Iota", "Cosmos", "Nem", "Zcash", "Dash", "Maker", "Compound", "Aave", "Synthetix",
            "Sushi", "Yearn", "Curve", "Balancer", "Bancor", "Ren", "Loopring", "Kyber", "0x", "Augur",
            "Basic", "Attention", "Token", "Enjin", "Decentraland", "Mana", "Sand", "Axie", "Gala", "Alice",
            "Illuvium", "Flow", "Audius", "Chiliz", "Wax", "Theta", "Filecoin", "Storj", "Siacoin", "Arweave",
            "Helium", "Holo", "BitTorrent", "Ocean", "Ankr", "Dent", "Pundi", "Reef", "Celer", "Matic",
            "Fantom", "Harmony", "Near", "Elrond", "Algorand", "Hedera", "Zilliqa", "Icon", "Ontology", "OmiseGo",
            "Qtum", "Lisk", "Nano", "Waves", "DigiByte", "Verge", "Raven", "Komodo", "Ark", "Steem"
        ]
    };
})();
