(function() {
    class DragonTowerGame {
        constructor(containerId, currency = 'cash') {
            this.container = document.getElementById(containerId);
            this.currency = currency;
            this.difficulty = 'medium'; // easy (3/4), medium (2/3), hard (1/2)
            this.rows = 9;
            this.cols = 3; // Default for medium
            this.currentRow = 0;
            this.inGame = false;
            this.bet = 0;
            this.multipliers = [];
            
            this.setupUI();
            this.bindEvents();
            this.calculateMultipliers();
        }
        
        calculateMultipliers() {
            // Calculate based on difficulty
            // Easy: 4 cols, 1 bad. Win 3/4. Mult ~ 1.33
            // Medium: 3 cols, 1 bad. Win 2/3. Mult ~ 1.5
            // Hard: 2 cols, 1 bad. Win 1/2. Mult ~ 2.0
            // Expert: 3 cols, 2 bad. Win 1/3. Mult ~ 3.0
            
            let winChance, colCount;
            if (this.difficulty === 'easy') { colCount = 4; winChance = 3/4; }
            else if (this.difficulty === 'medium') { colCount = 3; winChance = 2/3; }
            else if (this.difficulty === 'hard') { colCount = 2; winChance = 1/2; }
            else { colCount = 3; winChance = 1/3; } // expert
            
            this.cols = colCount;
            let currentMult = 1;
            this.multipliers = [];
            
            for(let i=0; i<this.rows; i++) {
                currentMult = currentMult * (1/winChance) * 0.98; // 2% edge
                this.multipliers.push(parseFloat(currentMult.toFixed(2)));
            }
            
            this.updateTowerUI();
        }

        setupUI() {
            if (!this.container) return;
            
            this.container.innerHTML = `
                <div class="game-panel dragon-tower-game">
                    <div class="game-header">
                        <h2>Dragon Tower</h2>
                        <div class="balance-display">Balance: <span id="dt-balance">0.00</span></div>
                    </div>
                    <div class="game-visuals" style="display:flex; justify-content:center; padding:20px;">
                        <div id="dt-tower" style="display:flex; flex-direction:column-reverse; gap:5px;">
                            <!-- Rows generated by JS -->
                        </div>
                    </div>
                    <div class="game-controls">
                        <div class="input-group">
                            <label>Difficulty</label>
                            <select id="dt-diff" class="game-select">
                                <option value="easy">Easy (4 cols, 1 bad)</option>
                                <option value="medium" selected>Medium (3 cols, 1 bad)</option>
                                <option value="hard">Hard (2 cols, 1 bad)</option>
                                <option value="expert">Expert (3 cols, 2 bad)</option>
                            </select>
                        </div>
                        <div class="input-group">
                            <label>Bet Amount</label>
                            <input type="number" id="dt-bet" value="10" min="1" class="game-input">
                        </div>
                        <button id="dt-play" class="game-btn action-btn">Start Game</button>
                        <button id="dt-cashout" class="game-btn success-btn" disabled>Cashout</button>
                    </div>
                    <div id="dt-log" class="game-log"></div>
                </div>
            `;
            
            this.elements = {
                balance: this.container.querySelector('#dt-balance'),
                tower: this.container.querySelector('#dt-tower'),
                diffSelect: this.container.querySelector('#dt-diff'),
                betInput: this.container.querySelector('#dt-bet'),
                playBtn: this.container.querySelector('#dt-play'),
                cashoutBtn: this.container.querySelector('#dt-cashout'),
                log: this.container.querySelector('#dt-log')
            };
            
            this.updateBalanceDisplay();
        }
        
        updateTowerUI() {
            this.elements.tower.innerHTML = '';
            for(let r=0; r<this.rows; r++) {
                const row = document.createElement('div');
                row.className = 'tower-row';
                row.id = `row-${r}`;
                row.style.display = 'flex';
                row.style.gap = '5px';
                
                for(let c=0; c<this.cols; c++) {
                    const tile = document.createElement('div');
                    tile.className = 'tower-tile';
                    tile.dataset.row = r;
                    tile.dataset.col = c;
                    tile.style.width = '60px';
                    tile.style.height = '40px';
                    tile.style.background = '#444';
                    tile.style.borderRadius = '4px';
                    tile.style.cursor = 'pointer';
                    tile.style.display = 'flex';
                    tile.style.alignItems = 'center';
                    tile.style.justifyContent = 'center';
                    tile.innerHTML = r === 0 ? '<i class="fas fa-question"></i>' : ''; // Only show clickable on active?
                    
                    // Bind click
                    tile.addEventListener('click', () => this.selectTile(r, c));
                    row.appendChild(tile);
                }
                
                // Label
                const label = document.createElement('div');
                label.innerText = `${this.multipliers[r]}x`;
                label.style.marginLeft = '10px';
                label.style.alignSelf = 'center';
                label.style.fontSize = '0.8em';
                label.style.width = '40px';
                row.appendChild(label);
                
                this.elements.tower.appendChild(row);
            }
            this.highlightRow(0);
        }
        
        highlightRow(r) {
            // Dim all
            const rows = this.elements.tower.querySelectorAll('.tower-row');
            rows.forEach(row => row.style.opacity = '0.5');
            
            // Highlight current
            if (r < this.rows) {
                const active = this.elements.tower.querySelector(`#row-${r}`);
                if(active) {
                    active.style.opacity = '1';
                    active.style.boxShadow = '0 0 10px rgba(255,255,255,0.1)';
                }
            }
        }

        bindEvents() {
            this.elements.diffSelect.addEventListener('change', (e) => {
                if(this.inGame) return;
                this.difficulty = e.target.value;
                this.calculateMultipliers();
            });
            
            this.elements.playBtn.addEventListener('click', () => {
                if(!this.inGame) this.startGame();
            });
            
            this.elements.cashoutBtn.addEventListener('click', () => this.cashout());
        }
        
        getUserBalance() {
             if (typeof window.MK === 'undefined') return 0;
            return this.currency === 'cash' 
                ? (window.MK.state?.user?.balance || 0)
                : (window.MK.state?.user?.premiumBalance || 0);
        }

        updateBalanceDisplay() {
             this.elements.balance.innerText = this.getUserBalance().toFixed(2);
        }
        
        updateBalance(amount) {
            if (typeof window.MK !== 'undefined') {
                if (this.currency === 'cash' && window.MK.updateBalance) {
                     window.MK.updateBalance(amount);
                } else if (this.currency === 'gems' && window.MK.state && window.MK.state.user) {
                     window.MK.state.user.premiumBalance += amount;
                     if (window.MK.refreshUI) window.MK.refreshUI();
                }
            }
            this.updateBalanceDisplay();
        }

        log(msg, type='neutral') {
             const div = document.createElement('div');
            div.innerText = msg;
            div.className = `log-entry ${type}`;
             if (this.elements.log.firstChild) {
                this.elements.log.insertBefore(div, this.elements.log.firstChild);
            } else {
                this.elements.log.appendChild(div);
            }
        }

        async startGame() {
            const bet = parseFloat(this.elements.betInput.value);
            const bal = this.getUserBalance();
            if(isNaN(bet) || bet <= 0) return alert('Invalid bet');
            if(bal < bet) return alert('Insufficient funds');

            this.updateBalance(-bet);
            this.bet = bet;
            this.inGame = true;
            this.currentRow = 0;
            
            this.elements.playBtn.disabled = true;
            this.elements.diffSelect.disabled = true;
            this.elements.betInput.disabled = true;
            this.elements.cashoutBtn.disabled = true;
            
            this.updateTowerUI(); // Reset visual
            this.log(`Started game on ${this.difficulty}`, 'neutral');
        }

        async selectTile(r, c) {
            if(!this.inGame) return;
            if(r !== this.currentRow) return; // Must pick from current row
            
            // Determine result
            // Based on difficulty, how many bad eggs?
            let badCount = 1;
            if(this.difficulty === 'expert') badCount = 2;
            
            // Randomly assign bad spots in this row
            const badSpots = [];
            while(badSpots.length < badCount) {
                const spot = Math.floor(Math.random() * this.cols);
                if(!badSpots.includes(spot)) badSpots.push(spot);
            }
            
            const isBad = badSpots.includes(c);
            const tiles = this.elements.tower.querySelectorAll(`#row-${r} .tower-tile`);
            
            // Reveal all
            tiles.forEach((t, idx) => {
                if(badSpots.includes(idx)) {
                    t.innerHTML = '<i class="fas fa-dragon" style="color:#f44336"></i>'; // Dragon
                } else {
                    t.innerHTML = '<i class="fas fa-egg" style="color:#ffd700"></i>'; // Egg
                }
                
                if (idx === c) {
                     t.style.border = '2px solid #fff';
                }
            });
            
            await new Promise(r => setTimeout(r, 500));
            
            if(isBad) {
                this.log(`Dragon! Game Over.`, 'loss');
                this.endGame(false);
            } else {
                this.currentRow++;
                const mult = this.multipliers[r];
                this.log(`Cleared Row ${r+1}! Current Value: ${(this.bet * mult).toFixed(2)}`, 'success');
                
                if(this.currentRow >= this.rows) {
                    this.cashout(true);
                } else {
                    this.elements.cashoutBtn.disabled = false;
                    this.highlightRow(this.currentRow);
                    // Add question marks to next row
                    const nextRowTiles = this.elements.tower.querySelectorAll(`#row-${this.currentRow} .tower-tile`);
                    nextRowTiles.forEach(t => t.innerHTML = '<i class="fas fa-question"></i>');
                }
            }
        }
        
        cashout(auto=false) {
            if(!this.inGame) return;
            
            const r = this.currentRow - 1;
            if (r < 0) return;
            
            const mult = this.multipliers[r];
            const payout = this.bet * mult;
            
            this.updateBalance(payout);
            this.log(`Cashed out at ${mult}x! Won ${payout.toFixed(2)}`, 'win');
            this.endGame(true);
        }

        endGame(won) {
            this.inGame = false;
            this.elements.playBtn.disabled = false;
            this.elements.diffSelect.disabled = false;
            this.elements.betInput.disabled = false;
            this.elements.cashoutBtn.disabled = true;
        }
    }

    window.MoonKat = window.MoonKat || {};
    window.MoonKat.DragonTowerGame = DragonTowerGame;
})();
